# Generated by Django 4.2.3 on 2023-07-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventHubAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_verefied',
            new_name='is_verified',
        ),
    ]
