# Generated by Django 4.2.3 on 2023-07-19 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventHubAPI', '0002_rename_is_verefied_event_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventHubAPI.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='events', to='eventHubAPI.club'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_attendants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='university',
            field=models.ManyToManyField(blank=True, null=True, related_name='universities', to='eventHubAPI.university'),
        ),
        migrations.AlterField(
            model_name='event',
            name='wilaya',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
