# Generated by Django 4.2.3 on 2023-07-19 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventHubAPI', '0003_alter_event_body_alter_event_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='university',
            field=models.ManyToManyField(blank=True, related_name='universities', to='eventHubAPI.university'),
        ),
        migrations.AlterField(
            model_name='event',
            name='wilaya',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(58), django.core.validators.MinValueValidator(1)]),
        ),
    ]
