# Generated by Django 4.2.3 on 2023-07-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='university',
        ),
        migrations.AddField(
            model_name='club',
            name='university',
            field=models.ManyToManyField(null=True, to='events.university'),
        ),
    ]
