# Generated by Django 4.2.3 on 2023-07-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_club_university_club_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='university',
            field=models.ManyToManyField(blank=True, to='events.university'),
        ),
    ]
