# Generated by Django 4.2.3 on 2023-07-25 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_club_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='university',
        ),
        migrations.RemoveField(
            model_name='event',
            name='university',
        ),
        migrations.AddField(
            model_name='club',
            name='universities',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='events.university'),
        ),
        migrations.AddField(
            model_name='event',
            name='universities',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.university'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category'),
        ),
    ]
