# Generated by Django 4.2.3 on 2023-07-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_club_owner_alter_event_owner_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
