# Generated by Django 4.2.3 on 2023-07-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_duration_alter_club_image_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
