# Generated by Django 4.2.3 on 2023-07-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_category_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='body',
        ),
        migrations.AddField(
            model_name='university',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
