# Generated by Django 4.2.3 on 2023-07-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_category_body_university_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_start_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
