# Generated by Django 4.2.3 on 2023-07-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_event_start_date_event_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='location_name',
        ),
        migrations.AddField(
            model_name='event',
            name='location_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
