# Generated by Django 4.2.3 on 2023-08-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
