# Generated by Django 4.2.3 on 2023-08-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_id',
            field=models.CharField(default='R415866', max_length=255),
            preserve_default=False,
        ),
    ]
